application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "docker"
  password: "docker"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_miliseconds: 10000
